import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { COMPLIANCE_CATEGORIES } from '../data/complianceRules'

export function generateCompliancePDF(calendarData) {
  const { events, grouped, companyName, generatedOn, state } = calendarData
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 14
  const contentW = pageW - margin * 2

  // Cover header band
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, pageW, 55, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(companyName, margin, 24)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.text('12-Month Compliance Calendar', margin, 34)
  doc.setFontSize(9)
  doc.setTextColor(191, 219, 254)
  doc.text(`${state}  ·  Generated by Startup OS  ·  ${generatedOn}`, margin, 43)
  doc.text('Confidential', margin, 50)

  // Summary stats
  const critical = events.filter(e => e.urgency === 'critical').length
  const urgent = events.filter(e => e.urgency === 'urgent').length
  const summaryY = 65
  const cardW = (contentW - 12) / 4
  const statBoxes = [
    { label: 'Total Events', value: `${events.length}`, color: [30, 64, 175] },
    { label: 'Critical (< 7 days)', value: `${critical}`, color: [220, 38, 38] },
    { label: 'Urgent (< 21 days)', value: `${urgent}`, color: [180, 83, 9] },
    { label: 'Categories', value: `${new Set(events.map(e => e.category)).size}`, color: [21, 128, 61] },
  ]
  statBoxes.forEach((box, i) => {
    const x = margin + i * (cardW + 4)
    doc.setFillColor(245, 244, 240)
    doc.roundedRect(x, summaryY, cardW, 22, 2, 2, 'F')
    doc.setDrawColor(...box.color)
    doc.setLineWidth(0.5)
    doc.roundedRect(x, summaryY, cardW, 22, 2, 2, 'S')
    doc.setTextColor(...box.color)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(box.value, x + cardW / 2, summaryY + 10, { align: 'center' })
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text(box.label, x + cardW / 2, summaryY + 18, { align: 'center' })
  })

  // Important notice
  const noticeY = summaryY + 30
  doc.setFillColor(254, 242, 242)
  doc.setDrawColor(220, 38, 38)
  doc.setLineWidth(0.3)
  doc.rect(margin, noticeY, contentW, 14, 'FD')
  doc.setTextColor(220, 38, 38)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text('IMPORTANT:', margin + 3, noticeY + 5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 40, 40)
  doc.text('This calendar is personalised to your company. Penalties shown are per current Indian law. Consult your CA before all filings.', margin + 3, noticeY + 10)

  // Category legend
  const legendY = noticeY + 22
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('Categories', margin, legendY)
  const cats = Object.entries(COMPLIANCE_CATEGORIES)
  const catW = (contentW - (cats.length - 1) * 4) / cats.length
  cats.forEach(([, cat], i) => {
    const x = margin + i * (catW + 4)
    const [r, g, b] = hexToRgb(cat.color)
    doc.setFillColor(r, g, b)
    doc.rect(x, legendY + 3, 3, 3, 'F')
    doc.setTextColor(60, 60, 60)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text(cat.label, x + 5, legendY + 6)
  })

  // Monthly sections
  let currentY = legendY + 16
  const monthNames = Object.keys(grouped)

  monthNames.forEach((month) => {
    const monthEvents = grouped[month]
    const estimatedHeight = 10 + monthEvents.length * 9 + 8
    if (currentY + estimatedHeight > pageH - 20) {
      doc.addPage()
      doc.setFillColor(30, 64, 175)
      doc.rect(0, 0, pageW, 12, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.text(`${companyName}  ·  12-Month Compliance Calendar`, margin, 8)
      currentY = 20
    }

    // Month header
    doc.setFillColor(241, 244, 255)
    doc.setDrawColor(147, 197, 253)
    doc.setLineWidth(0.3)
    doc.rect(margin, currentY, contentW, 8, 'FD')
    doc.setTextColor(30, 64, 175)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(month, margin + 3, currentY + 5.5)
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(8)
    doc.text(`${monthEvents.length} event${monthEvents.length !== 1 ? 's' : ''}`, pageW - margin - 3, currentY + 5.5, { align: 'right' })
    currentY += 10

    const tableBody = monthEvents.map(event => [
      event.dueDateStr,
      event.title,
      event.form || '—',
      event.penalty,
    ])

    autoTable(doc, {
      startY: currentY,
      head: [['Due Date', 'Compliance Event', 'Form / Filing', 'Penalty if Missed']],
      body: tableBody,
      margin: { left: margin, right: margin },
      styles: { fontSize: 7.5, cellPadding: 2.5, lineColor: [216, 213, 207], lineWidth: 0.2, textColor: [28, 25, 23], font: 'helvetica' },
      headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      columnStyles: {
        0: { cellWidth: 25, fontStyle: 'bold' },
        1: { cellWidth: 70 },
        2: { cellWidth: 35 },
        3: { cellWidth: 52, textColor: [180, 83, 9] },
      },
      didParseCell: (data) => {
        if (data.section === 'body') {
          const event = monthEvents[data.row.index]
          if (event?.urgency === 'critical') {
            data.cell.styles.fillColor = [254, 242, 242]
            data.cell.styles.textColor = [180, 30, 30]
          } else if (event?.urgency === 'urgent') {
            data.cell.styles.fillColor = [255, 251, 235]
          }
          if (event?.critical && data.column.index === 1) {
            data.cell.styles.fontStyle = 'bold'
          }
        }
      },
    })

    currentY = doc.lastAutoTable.finalY + 6
  })

  // Footer on all pages
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.3)
    doc.line(margin, pageH - 10, pageW - margin, pageH - 10)
    doc.setTextColor(150, 150, 150)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text(`${companyName}  ·  Compliance Calendar  ·  Generated by Startup OS`, margin, pageH - 6)
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 6, { align: 'right' })
  }

  return doc
}

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : [0, 0, 0]
}
